### ISSUE TITLE
Étrange code HTTP

### ISSUE THREAD

**Issue by yoannfleurydev** [M2GIL/IAtaaa-server#2]
Lorsque j'envoie deux fois un objet `Player` avec le même nom, l'API me renvoie bien un message d'erreur dans le *body*, mais pas le bon code HTTP dans le *header*. Ici, je vois bien une 400 `BAD REQUEST` plutôt qu'une 200 `OK` qui donne l'impression que tout s'est bien passé.

![200ok](https://cloud.githubusercontent.com/assets/3920615/21460063/99e03564-c944-11e6-81ef-da66d693c1f7.png)

**Comment by AnthoGdn** [comment]
Bug corrigé et pousser sur dev merci !
