### ISSUE TITLE
Incorrect players

### ISSUE THREAD

**Issue by yoannfleurydev** [M2GIL/IAtaaa-server#4]
![image](https://cloud.githubusercontent.com/assets/3920615/22628458/9fb3ac0c-ebd4-11e6-9239-11631bffc11f.png)

The players inside the web socket are incorrect. My players are named **Coucou1** and **Coucou2**, but inside the web socket, they have no name and incorrect URLs

**Comment by yoannfleurydev** [comment]
In the new version, it's better, but players are named *toto* :disappointed:

**Comment by z3ddycus** [comment]
The field name has been added to the web player. Not sure if the test player return the good value but the websocketplayer seems to be fixed. <3 coeur - coeur <3
