### ISSUE TITLE
Can't add a game anymore

### ISSUE THREAD

**Issue by yoannfleurydev** [M2GIL/IAtaaa-server#5]
Since the last change on the server, I can't add a game anymore. This is the output of the server : 

![server-output](https://cloud.githubusercontent.com/assets/3920615/22666125/b9479b9a-ecb7-11e6-98dd-51e2fa9af687.png)

This is the response I have with my REST Client Insomnia : 

**409 INVALID**
```json
{
	"content": {
		"gameID": "M1D2",
		"players": [
			"M1",
			"D2"
		]
	},
	"status": "BUSY_IA"
}
```

Here is the screenshot : 

![client-output](https://cloud.githubusercontent.com/assets/3920615/22666474/fa2a4346-ecb8-11e6-8f5f-b5a44185e811.png)

**Comment by z3ddycus** [comment]
fixed with the fix of the issue "#4 incorrect player".
<3 coeur - coeur <3
